/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./frontend/**/*.html",
    "./frontend/**/*.js"
  ],
  theme: {
    extend: {
      colors: {
        "surface-bright": "var(--color-surface-bright, #f8f9fb)",
        "secondary-container": "var(--color-secondary-container, #e2dfde)",
        "tertiary": "var(--color-tertiary, #505b6d)",
        "inverse-primary": "var(--color-inverse-primary, #ffb4ac)",
        "on-primary-fixed": "var(--color-on-primary-fixed, #410003)",
        "on-primary": "var(--color-on-primary, #ffffff)",
        "error-container": "var(--color-error-container, #ffdad6)",
        "secondary-fixed": "var(--color-secondary-fixed, #e5e2e1)",
        "secondary": "var(--color-secondary, #5f5e5e)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant, #474746)",
        "primary-container": "var(--color-primary-container, #d9302f)",
        "inverse-on-surface": "var(--color-inverse-on-surface, #f0f1f3)",
        "on-background": "var(--color-on-background, #191c1e)",
        "inverse-surface": "var(--color-inverse-surface, #2e3132)",
        "surface-variant": "var(--color-surface-variant, #e1e2e4)",
        "outline-variant": "var(--color-outline-variant, #e4beb9)",
        "surface-tint": "var(--color-surface-tint, #bb171d)",
        "on-tertiary-container": "var(--color-on-tertiary-container, #f9f9ff)",
        "surface": "var(--color-surface, #f8f9fb)",
        "on-secondary-container": "var(--color-on-secondary-container, #636262)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim, #c8c6c5)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim, #ffb4ac)",
        "surface-container-low": "var(--color-surface-container-low, #f2f4f6)",
        "on-error": "var(--color-on-error, #ffffff)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "tertiary-container": "var(--color-tertiary-container, #697386)",
        "primary": "var(--color-primary, #d9302f)",
        "primary-dark": "var(--color-primary-dark, #82010e)",
        "error": "var(--color-error, #ba1a1a)",
        "on-surface-variant": "var(--color-on-surface-variant, #5b403d)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim, #bdc7dc)",
        "surface-container": "var(--color-surface-container, #edeef0)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed, #1c1b1b)",
        "on-secondary": "var(--color-on-secondary, #ffffff)",
        "surface-container-highest": "var(--color-surface-container-highest, #e1e2e4)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #3d4759)",
        "on-surface": "var(--color-on-surface, #191c1e)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant, #93000e)",
        "background": "var(--color-background, #f8f9fb)",
        "surface-dim": "var(--color-surface-dim, #d9dadc)",
        "on-tertiary": "var(--color-on-tertiary, #ffffff)",
        "tertiary-fixed": "var(--color-tertiary-fixed, #d9e3f9)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed, #121c2c)",
        "primary-fixed": "var(--color-primary-fixed, #ffdad6)",
        "on-primary-container": "var(--color-on-primary-container, #fff8f7)",
        "outline": "var(--color-outline, #906f6c)",
        "on-error-container": "var(--color-on-error-container, #93000a)",
        "surface-container-high": "var(--color-surface-container-high, #e7e8ea)",
        "charcoal": "var(--color-charcoal, #191c1e)",
        "navy-grey": "var(--color-navy-grey, #2d3748)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant, #454747)"
      },
      borderRadius: {
        "DEFAULT": "var(--rounded-default, 0.25rem)",
        "lg": "var(--rounded-lg, 0.5rem)",
        "xl": "var(--rounded-xl, 0.75rem)",
        "full": "var(--rounded-full, 9999px)"
      },
      spacing: {
        "sm": "12px",
        "lg": "48px",
        "margin-desktop": "64px",
        "md": "24px",
        "margin-mobile": "16px",
        "base": "8px",
        "xs": "4px",
        "xl": "80px",
        "gutter": "24px",
        "section-padding": "96px"
      },
      fontFamily: {
        "label-bold": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "Inter", "sans-serif"],
        "display-lg": ["Montserrat", "Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Montserrat", "Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-technical": ["JetBrains Mono", "monospace"],
        "measurement-sm": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "label-bold": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "700"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "display-lg": ["clamp(48px, 8vw, 80px)", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "headline-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
        "headline-xl": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "headline-xl-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "label-technical": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "500" }],
        "measurement-sm": ["10px", { "lineHeight": "12px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries")
  ]
}
